### PR TITLE
Orca visual tweaks and bug fixes

### PR DESCRIPTION
**Pull request by NotWendy**
General gameplay changes:
- Made bots no longer idle in the room with the diving suits and a window by marking it as airlock access. This is the most dangerous room in the entire submarine and the bots should treat it as such. This should help Orca complete personnel transport missions more reliably.
- Removed the remaining railgun shell rack from the gunnery and rearranged other gunnery items using that space.
- Linked the medical fabrication cabinet (medium steel cabinet) in the medbay to the medical fabricator, keeping it consistent with the regular fabricator.
- Unchecked "display side by side when linked" on the regular fabricator. Kept it checked on the cabinet itself. You can see the cabinet's contents when interacting with the fabricator, but you don't see the fabrication menu when interacting with the cabinet itself. Makes sorting through the cabinet's contents easier without another menu always being on your screen.
- Stopped the 3D nose piece from flooding the crew quarters when broken. I'm not 100% sure about this change, but seeing water flow through an intact inside wall due to the broken 3D piece's gap overlapping it feels wrong.
- Prevented undrainable water from staying in the engineering compartment by turning the whole room into one hull box.
- Simplified the bottom docking hatch by turning it into a single hull box as well. Adjusted the wiring of the pump placed there to ensure it pumps out all the water and doesn't leave a bit undrained. The wiring here isn't exactly standard for the base game, but it is still simple.
- Rearranged the command room a little.
- Replaced the custom door in the top airlock with a "door with buttons" assembly, making it easier to interact with.
- Removed the camera above the searchlight. From what I can tell, absolutely nothing changed in how the player's fov behaves when using the searchlight alone.
- Removed one fire extinguisher in the reactor room. Two extinguishers in one room is an overkill.

Wiring and lighting changes:
- Moved the flood alarm circuit into a circuit box, located in the front junction box room. Made it activate only when the combined water% of the water detectors is greater than 10. Hearing the alarm as soon as a drop of water makes it into the submarine is unpleasant and it's a situation that comes up all the time.
- Exposed the Wi-Fi component in the reactor room by moving it out of the ceiling.
- Made Orca's ambient lighting less bright. (20 alpha instead of 50, with 20 being the standard value used across most submarines.)
- Removed the lamp in the armory, replaced it by an emergency light.
- Added a second lamp in the reactor room.
- Added an emergency light behind the oxygen generator. Previously it was only visible thanks to the aggressive ambient lighting.
- Made the exterior lights slightly less bright.
- Removed bright lights hidden in the shell pieces around the top docking hatch, kept one light marking where the airlock button is.
- Moved the two emergency lights in the gunnery from loaders to ammo shelves.
- Other small lighting adjustments, such as making the main lamp in the gunnery dimmer.

Visual changes:
- Leaning heavily on the idea of Orca being a product of a whole lot of retrofitting. A submarine which used to be neat and organized, but over time turned into a bit of a mess, trying to keep up with the competition. The background wall in the gunnery has been replaced with something looking like a temporary solution, more rust has been added in a few places, some extra boxes and pipes here and there.
- "Large horizontal back" decorations are used as cable holders in some rooms.
- The wall in the engineering compartment has been replaced with a mix of panels and Back Wall C1.
- More decorations behind the oxygen generator, filling in the space.
- Navigation icons are now placed on top of plaques.
- Reactor cabinet is now marked with a nuclear sign, making it more obvious which cabinet bots consider to be an appropriate place for the reactor fuel.
- Added metal strips around exterior hatches.
- All exterior decorations have been reworked.
- Fixed some sprite depth issues.
- Disabled drop shadows on everything except for the 3D pieces. They clash heavily with the actual lighting effects and look unnatural.

OrcaRework

OrcaReworkRooms

OrcaReworkLighting

### CODE REVIEW

**Comment by JeroonBosch** [comment]
Thanks for your submission, we'll take a look once we get around to it. What tests did you do with the sub yourself? Did you complete some rounds with bots and players?

**Comment by NotWendy** [comment]
> Thanks for your submission, we'll take a look once we get around to it. What tests did you do with the sub yourself? Did you complete some rounds with bots and players?

I've played through the first few missions of the singleplayer campaign with it. Went through some cargo missions, as well as some combat, during which enemies breached and entered the submarine. Bots handled it okay.
Also tested flooding different areas of the sub with a plasma cutter, to see how it floods and drains.
And I made bots follow me around the submarine for a while, making sure they don't get stuck while navigating between rooms.
Haven't found any issues with crew or enemy AI. I haven't had a chance to do any multiplayer tests yet.

**Comment by PanmanS** [comment]
Horrendous hulls still are there

**Comment by mygamingaccount** [comment]
> Horrendous hulls still are there

Thanks for the entirely unproductive comment. Next time instead of commenting just don't.

**Comment by NotWendy** [comment]
Closing this PR to redo it later.

**Pull request closed without merging**
