### PR TITLE
Dugong rework

### PR DESCRIPTION
**Pull request by Waylonek**
First off English is not my native language, there may be translation inaccuracies.

My desire was to make vanilla sub more attractive without "over-decorate" it. The rework emphasizes decoration and combining elements with the wall pattern + fit wall's pattern borders in room.

### Changes :
1.  Decreased docking port section
2.  Filled space in the bow of sub -> moved ballast forward while keeping neutral level [0.5213->0.5183]
3.  Removed small step-wall above the ceiling at the bottom of the boat
4.  Due to increased bottom floor -> reactor compartment reduced, oxygen generator moved to the right, intermediate compartment with crate shelfs added, juncboxes moved slightly to the right into a separate compartment.
5.  All circuit "or" moved to circuit box + added siren switch (for disable annoying siren-water-flow sound).
6.  Ballast "decorative columns" now a bit usable(can pump out water by button, second push return back normal sub control)
7.  Added medical bed at medbay
8.  Engine's ladder is now unnecessary -> height is sufficient for climbing via "W-button" + and easter-egg for clown with bike horn on floor
9.  Changed diving suits holder: 1 holder near captain, double rack for diving suits in center and near airlock
10. External and internal lighting made in 3 colors(red, candle and light gray) with alpha 100-125, except ballast and ohygen rooms with 75. Ballast and exterior lamps are pulse. Near engine flicker a bit.
11. navigational terminal connected to status monitor(but if open status monitor - it will be alone[for more comfort searching]).
12. Informational displays, lamps and sirens near captain combine in column.
13. Moved second ammunition shelf from armory to periscopes(most people just throw boxes near loaders)
14. Duct system cover all sub evenly.
15. Was made small correction of sub shell shape and fins.

### Disputable solutions:
1.  Side drain in engine's room (works through circuit "greater" and 2 water detectors) 
2.  All relays for diving suits, lamps, battery array and docking hatch under juckbox(don't hide in walls). Relays are "unholdable".
3.  Entrance to front ballast from armory, not medbay.
4.  Usable decorative columns.

dugong

dugong_light

dugong_compare

### CODE REVIEW

**Comment by NotWendy** [comment]
I don't think such intrusive changes can count as a rework. This is a new submarine.

**Comment by meatball133** [comment]
Sure it can't count as "improvements", and rework is likely a fitting name.

Since this is far from a new submarine, does it feature mostly the same layout and design? yes. The difference is that one ballast room entrance has moved and some smaller adjustments to room sizes. As well as have the cargo moved from the engine room to electrical.

**Comment by PanmanS** [comment]
ngl anything bug dugong and humpback.

**Comment by ubertpendragon** [comment]
Very clean rework but I don't like having to go to the armory to access the ballast as someone would want to lock it

**Comment by Waylonek** [comment]
> Very clean rework but I don't like having to go to the armory to access the ballast as someone would want to lock it

Dugong armory is unlocked, as i remember, only secure cabinet.At current moment I can't move hatch to medbay without  changing 3 others rooms(if i want save duct to oxygen) or removing railgun shelf 
изображение

**Comment by mygamingaccount** [comment]
Lore _specifically_ states there is no seating in the conn.

**Pull request closed without merging**
