### PR TITLE
Riot Helmet Resprite

### PR DESCRIPTION
**Pull request by EebleSheembl**
Resprites the Riot Helmet to be more of a riot helmet and less of a football helmet

image
image

### CODE REVIEW

**Review by Regalis11 — CHANGES_REQUESTED** [review]
There seem to be changes to Moping Jack in this PR that don't seem to be related to it.

I also feel the sprite needs more work: there's some strange blur at the top-left corner and some kind of artifacts around the edges (black "outline" on top, white edges in some spots?)

**Comment by bananaman6213** [comment]
For what it's worth, I use the riot helmet specifically beacuse of how it looks right now. The football helmet design is silly enough that I'd still use the thing if you gave it chitin helmet's awful stats.
I know it's not worth rejecting a PR based on the input of one person, but this does sadden me

**Comment by NotWendy** [comment]
I wouldn't consider the sprite in this PR to be a direct improvement. The current base game riot helmet may look like a questionable piece of protective equipment, compared to the ballistic helmet, but it's at least clear what kind of design the artist was going for.
The sprite in the PR is a strange combination of an American football helmet and a real life riot helmet.

**Comment by EebleSheembl** [comment]
> The sprite in the PR is a strange combination of an American football helmet and a real life riot helmet. Two different identities fighting for dominance within a single sprite.

When I was looking at references for making this I found helmets with a cage, visor, both, and none and chose to do one with both

**Comment by EebleSheembl** [comment]
> There seem to be changes to Moping Jack in this PR that don't seem to be related to it.

Don't know how this happened but I presume it's from how I did the PR since I'm new to doing this and I'm kinda just guessing how to do it

**Comment by EebleSheembl** [comment]
> I also feel the sprite needs more work: there's some strange blur at the top-left corner and some kind of artifacts around the edges (black "outline" on top, white edges in some spots?)

Is this one better?
image

**Comment by EebleSheembl** [comment]
Does github do anything to images or anything since theres some things that ain't there but are on that image like those white outlines

**Comment by EebleSheembl** [comment]
> > There seem to be changes to Moping Jack in this PR that don't seem to be related to it.
> 
> Don't know how this happened but I presume it's from how I did the PR since I'm new to doing this and I'm kinda just guessing how to do it

fixed it

**Comment by Regalis11** [comment]
On a second thought, I agree with NotWendy and bananaman6213. I believe it was the artists intention that it looks like a football helmet. Yes, it is silly, but some people may prefer to wear silly-looking gear, and those who don't can choose from the other options. I also feel it's entirely plausible they'd be using football helmets (or what look like football helmets) as protective gear on Europa - perhaps they got some from Earth, and they're cheap, light and work alright as riot gear.

**Pull request closed without merging**
