### PR TITLE
Berilia Improvements and Fixes

### PR DESCRIPTION
**Pull request by WJohn**
With the advent of the newly updated Berilia and with the Traitor rework, a number of minor issues became apparent to me through further playtime, and with the mashed-together versions it ended up with. This PR aims to fix up some lingering issues, and more importantly, make it a more desirable Submarine for large player counts.

<details><summary><b>Changelist and reasoning:</b></summary>
<p>
<li><b>Turned the empty hallway between the Engine and central Junctions room into a bar/smoke lounge in the center of the ship. This bar also boasts a crucial new ability: a Vending Machine.</b> The hallway was virtually unused outside of a grow-room, and should give players a place to form friendships and bonds in a large crew. More importantly, the Vending Machine uniquely gives the Berilia more late-game sustainability and independence from other ships, similar to the Winterhalter. This effectively means that, if the crew has money to spare, they can buy a few overpriced Opium bottles, Ethanol, or other essentials in a pinch when stations are few and far between.</li>
<li><b>Swapped the central Junctions room and empty hallway.</b> Would've been awkward to go through the Junctions room to reach the bar from the central ladder access.</li>
<li><b>Added a bottom docking port in the lower airlock.</b> Larger ships benefit more from multiple docking angles, and this ship here's the biggest. This necessitated adjusting of the Flak Cannon and its firing angles as to avoid clipping with shuttles.</li>
<li><b>Made the armory a bit bigger, carries two extra ammo box racks.</b> Was overly cramped, required lightly shifting the Medbay and Gunnery to the left, but nothing drastic.</li>
<li><b>Added more windows in the major hallways.</b> Easy to feel boxed in and separated from the outside on this ship, and the Typhon 2 is stealing all the good views of the endgame.</li>
<li><b>Replaced cameras on outside of ship with searchlights, like the R-29.</b> Searchlights have much greater view range, and the cameras just did not see far enough to be all that useful.</li>
<li><b>Replaced airlocks with no-rubberband version from PR #12358.</b> Bots are now able to enter/exit ship without any problem.</li>
<li><b>Simplified battery setup, made battery relays non-pickable.</b> As with other ships.</li>
<li><b>Slight increase of reactor output from 6700 to 6800.</b> To compensate for new searchlights.</li>
<li><b>Cargo Bay's left entrance now leads to upper engine, rather than Junctions room.</b> Avoids dumping water right into all the electrics in case of flooded cargo bay.</li>
<li><b>Adjusted bottom central hallway vs bottom airlock access lengths.</b> Lower airlock access' room length was way too long.</li>
<li><b>Slight adjustment to the far wall in the crew quarters.</b> The bow of the ship was two centimeters off from being able to behave as an extra layer of armor, and got flooded non-stop any time it got grazed.</li>
<li><b>Can now stand on the tables in the crew quarters/bar.</b> The rum bottle always fell through the table. I had considered a weapon holder, but this option can lead to entertaining crew theatrics.</li>
<li><b>Adjusted a lot of Junction wiring.</b></li>
<li><b>Minor aesthetic cleanup/consistency/visual tweaks throughout the ship.</b></li>
<li><b>Adjusted submarine description to mention four ballasts, instead of three.</li>
</p>
</details> 

<b>Pictures:</b>
Berilia
Berilia_lighting
Berilia_Bar

### CODE REVIEW

**Comment by mygamingaccount** [comment]
Did you test the lower docking port if it extends far enough to allow the vanilla respawn shuttles to dock?

**Comment by WJohn** [comment]
As some people have pointed out, the bottom Airlock sits uncomfortably close to the gun, resulting in clipping (and general difficulty of docking due to being recessed). I've gone and done a mockup of a possible alternative, though this adjusts the gun's firing angles noticeably, and makes the belly of the ship and the airlock more exposed, although EDC on the bottom of the ship can probably take care of most things.
berilia_adjusted

I won't push for this unless Jeroon decides this balance change is appropriate in the name of easier docking and no clipping issues.

**Comment by JeroonBosch** [comment]
Bottom docking ports are currently limited to the Kastrull, Orca 1, R-29 and both Typhons, so I wouldn't say a docking port is mandatory in the first place. I do agree though that a clipping turret isn't something I'd merge.

Personally I think moving the Flak cannon could be a decent solution, assuming it doesn't still clip while in that spot. It's either that or removing the docking hatch altogether, or moving it to the back (where the engine is)

**Comment by WJohn** [comment]
I believe adding a bottom docking port makes sense on the Berilia because it is by far the largest submarine in the game, and larger submarines really need the extra docking space.

And yes, I've checked, the turret no longer clips at that angle. Moving it to the back engine is a possible solution as well, though that's rather ugly and out of the way.

**Comment by JeroonBosch** [comment]
Hi WJohn, I will be closing this PR as I copied the file over to our local repo and there's no need to have two PRs open. Thank you for your submission.

**Pull request closed without merging**
